name: Run tests

on: [push, pull_request]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Install Dependencies
        run: composer install -n --prefer-dist

      - name: Install NPM Packages
        run: npm install

      - name: Build Assets
        run: npm run build

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache

      - name: Setup Sqlite
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Set SQLite Database in .env
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=$(pwd)/database/database.sqlite" >> .env

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test
